apiVersion: v1
kind: Service
metadata:
  name: vadim-test-page-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 8282
      protocol: TCP
      targetPort: 80
  selector:
    app: vadim-test-page-lb